Plugin-Enable: true
Maxi-People-In-A-Team: 4
Minimum-Number-Of-People-In-The-Lobby-To-Vote: 2
Block-Commands: false
Auto-Start-Players: 4
Auto-Start-Time: 60
Chests:
  Spawn-Chests:
      ItemID/Amount:
        - 270,1
        - 79, 2
        - 327,1
        - 346,1
        - 103,1
        - 331,24
        - 70,1
        - 29,2
        - 33,2
        - 299,2
        - 352,4
        - 295,2
        - 6,1
        - 81,3
        - 289,1
        - 75,1
        - 77,1
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
  Side-Chests:
      ItemID/Amount:
        - 360,6
        - 331,6
        - 262,8
        - 30,2
        - 280,3
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
  Middle-Chest:
      ItemID/Amount:
        - 313,2
        - 262,32
        - 280,2
        - 331,6
        - 264,1
        - 287,6
        - 277,1
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -
        -